#+title: Emacs configuration
#+author: Arnav Andrew Jose

This emacs config was originally for my work system.
I opted to start afresh and not copy over any
configuration from my personal machine(s).
It is now my primary configuration.
I am trying to keep it as minimalist and
low-fuss as possible.

* Before loading Init.el
  :PROPERTIES:
  :header-args: :tangle ~/.emacs.d/early-init.el
  :END:

** Disabling package.el and using straight.el instead
  #+begin_src emacs-lisp
    ;; source: https://github.com/crmsnbleyd/dotfiles
    (setq package-enable-at-startup nil)
  #+end_src

* Personal elisp functions
  :PROPERTIES:
  :header-args: :tangle ~/.emacs.d/lisp/functions.el :mkdirp yes
  :END:
  These might not be that useful for your specific use-case
** Enable lexical-binding
#+begin_src  emacs-lisp
  ;;; functions.el --- a simple package  -*- lexical-binding: t; -*-

  ;; Copyright (C) 2023  Drew Jose

  ;; Author: Drew Jose <arnav.jose@gmail.com>
  ;; Keywords: lisp
  ;; Version: 0.0.1

  ;; This program is free software; you can redistribute it and/or modify
  ;; it under the terms of the GNU General Public License as published by
  ;; the Free Software Foundation, either version 3 of the License, or
  ;; (at your option) any later version.

  ;; This program is distributed in the hope that it will be useful,
  ;; but WITHOUT ANY WARRANTY; without even the implied warranty of
  ;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ;; GNU General Public License for more details.

  ;; You should have received a copy of the GNU General Public License
  ;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

  ;;; Commentary:

  ;; Convenience functions for me

  ;;; Code:
  (require 'subr-x)
#+end_src

** Complete for eshell history in minibuffer (good with vertico)
#+begin_src emacs-lisp
  ;;;###autoload
  (defun functions/eshell-history-complete ()
    (interactive)
    (let ((to-input (completing-read
	     "Eshell history: "
	     (delete-dups
	      (ring-elements eshell-history-ring)))))
      (end-of-line)
      (eshell-kill-input)
      (insert to-input)))
#+end_src

** Insert metadata for Pelican markdown files
Really hardcoded right now
#+begin_src emacs-lisp
  ;;;###autoload
  (defun functions/pelican-metadata-insert ()
    (interactive)
    (let
	((date-string (format-time-string "%Y-%m-%d %H:%M"))
	 (slug (string-remove-suffix ".md" (buffer-name))))
      (insert
       (format
	"Title:
  Date: %s
  Modified: %s
  Tags:
  Category:
  Slug: %s
  Authors:
  Status: draft
  Summary:"
	date-string date-string slug))))
#+end_src
** Load some words for monkeytype
#+begin_src emacs-lisp
  (defun functions/monkeytype-load-and-start (arg &optional file-name num-words)
    (interactive "p")
    (when (/= arg 1)
      (setf file-name (read-file-name "Insert name of file with words: "))
      (setf num-words (read-number "Insert number of words you require: " 50)))

    (let ((res '())
	  (final-buffer "*Monkeytype-words*"))

      (with-temp-buffer
	(insert-file-contents
	 (or file-name
	     (expand-file-name
	      "wikipedia2k.txt"
	      "~/.monkeytype")))

	(setq res
	      (cl-loop repeat (or num-words 50)
		       for idx in (sort
				   (cl-loop for i from 0 to 49
					    collect (random 2000))
				   '<)
		       collect
		       (progn
			 (goto-char (point-min))
			 (forward-word idx)
			 (buffer-substring-no-properties
			  (point)
			  (progn (forward-word) (point)))))))

      (with-current-buffer (get-buffer-create final-buffer)
	(erase-buffer)
	(insert (string-trim-left
		 (mapconcat 'identity res)
		 " ")))
      (switch-to-buffer final-buffer)
      (monkeytype-buffer)))
#+end_src

** Provide package
#+begin_src  emacs-lisp
  (provide 'functions)
  ;;; functions.el ends here
#+end_src
* Emacs config
  :PROPERTIES:
  :header-args: :tangle ~/.emacs.d/init.el
  :END:

** Enable lexical-binding and add link to repo
#+begin_src  emacs-lisp
  ;; -*- lexical-binding: t -*-
  ;; source: https://github.com/crmsnbleyd/dotfiles
#+end_src
** Using convenience functions
#+begin_src emacs-lisp
  (use-package functions
    :commands
    (functions/eshell-history-complete
     functions/monkeytype-load-and-start
     functions/pelican-metadata-insert)
    :ensure nil
    :load-path "lisp")
#+end_src
** Using straight.el
Bootstrapping it, installing use-package and then
setting straight as the package manager for use-package.

  #+begin_src emacs-lisp
    (defvar bootstrap-version)
    (let ((bootstrap-file
	   (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
	  (bootstrap-version 6))
      (unless (file-exists-p bootstrap-file)
	(with-current-buffer
	    (url-retrieve-synchronously
	     "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
	     'silent 'inhibit-cookies)
	  (goto-char (point-max))
	  (eval-print-last-sexp)))
      (load bootstrap-file nil 'nomessage))

    ;; Install use-package if not bundled
    (when (version< emacs-version "29.0")
      (straight-use-package 'use-package))

    ;; use-package will use straight.el by default
    (use-package straight
      :custom
      (straight-use-package-by-default t))
  #+end_src

** Combobulate
Paredit + Tree-sitter! [[https://github.com/mickeynp/combobulate][Github]]
#+begin_src emacs-lisp
  (use-package combobulate
    :when (treesit-available-p)
    :straight (combobulate
	       :type git
	       :host github
	       :repo "mickeynp/combobulate")
    :hook
    ((go-ts-mode python-ts-mode yaml-ts-mode)
     . combobulate-mode))
#+end_src
** Completion and hide-show minor mode
z-c is hide-show close and z-o is hide-show open
#+begin_src emacs-lisp
  (use-package hideshow
    :hook (prog-mode . hs-minor-mode))

  (use-package corfu
    ;; Optional customizations
    :custom
    (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
    (corfu-auto t)                 ;; Enable auto completion
    (corfu-separator ?\s)          ;; Orderless field separator
    ;; (corfu-quit-at-boundary nil)   ;; Never quit at completion boundary
    ;; (corfu-quit-no-match nil)      ;; Never quit, even if there is no match
    ;; (corfu-preview-current nil)    ;; Disable current candidate preview
    ;; (corfu-preselect 'prompt)      ;; Preselect the prompt
    ;; (corfu-on-exact-match nil)     ;; Configure handling of exact matches
    ;; (corfu-scroll-margin 5)        ;; Use scroll margin

    ;; Enable Corfu only for certain modes.
    ;; :hook ((prog-mode . corfu-mode)
    ;;        (shell-mode . corfu-mode)
    ;;        (eshell-mode . corfu-mode))

    ;; Recommended: Enable Corfu globally.
    ;; This is recommended since Dabbrev can be used globally (M-/).
    ;; See also `global-corfu-modes'.
    :init
    (global-corfu-mode))
#+end_src
** Using ripgrep with emacs
#+begin_src emacs-lisp
  (use-package deadgrep
    :bind
    (("<f5>" . deadgrep)))
#+end_src
** Doom-modeline
Modern and pretty modeline. Does not work well in TUI.
Run ~nerd-icons-install-fonts~ to install the required pretty
icons on your system (unless you wish to disable them)
#+begin_src emacs-lisp
  (use-package doom-modeline
    :hook (after-init . doom-modeline-mode))
#+end_src
** Evil setup (Vi bindings)
Evil is vim emulation for emacs.
evil-mode initializes on startup.

evil-escape simulates <ESC> key in non-normal states
when pressing 'evil-escape-key-sequence.

evil-leader works in motion and normal states.
Press <leader> and the set-key to use the function.

undo-fu for vi-like undo and redo functionality

avy for tree-like jump to marks : [[https://github.com/abo-abo/avy][Avy project page]]
#+begin_src  emacs-lisp
  (use-package evil
    :config
    (evil-define-key 'normal org-mode-map
      (kbd "<tab>") #'org-cycle)
    (evil-define-key nil eshell-mode-map
      (kbd "M-r") #'eshell-history-complete)
    (define-key evil-normal-state-map
		(kbd "g s s") 'evil-avy-goto-char-2)
    :custom
    (evil-move-beyond-eol t)
    :hook (after-init . evil-mode))

  (use-package evil-escape
    :after (evil)
    :config
    (evil-escape-mode)
    :custom
    (evil-escape-key-sequence "jk")
    (evil-escape-delay 0.2))

  (use-package evil-leader
    :after (evil)
    :config
    (global-evil-leader-mode t)
    (evil-leader/set-leader "<SPC>")
    (evil-leader/set-key
      "." 'find-file
      ;; ";" 'comment-or-uncomment-region
      ;; deprecated in favour of calling M-; `comment-dwim'
      "z" 'repeat
      "d x w" 'delete-trailing-whitespace
      "f s" 'save-buffer
      "p f" 'forward-sexp
      "p b" 'backward-sexp
      "p t" 'transpose-sexps
      "r b" 'revert-buffer))

  (use-package evil-surround
    :after (evil)
    :config (global-evil-surround-mode))

  (use-package undo-fu
    :straight
    (undo-fu :type git :host github :repo "emacsmirror/undo-fu")
    :bind
    (("C-z" . undo-fu-only-undo)
     ("C-S-z" . undo-fu-only-redo))
    :custom
    (evil-undo-system 'undo-fu))

  (use-package avy
    :custom
    (avy-keys '(?a ?s ?f ?j ?k ?l ?z ?x ?c)))
#+end_src

** Exec path to reflect shell PATH variable
Otherwise we have to resort to silly hacks.
#+begin_src emacs-lisp
(use-package exec-path-from-shell
  :when (or (memq window-system'(mac ns x))
	    (daemonp))
  :config (exec-path-from-shell-initialize))
#+end_src
** Flexoki themes
I made this theme!
#+begin_src emacs-lisp
  (use-package flexoki-themes
    :config (load-theme 'flexoki-themes-light t))
#+end_src
** Learning to touch type
[[https://github.com/jpablobr/emacs-monkeytype][Monkeytype]]
#+begin_src emacs-lisp
  (use-package monkeytype
    :defer t)
#+end_src
** Magit (git porcelain)
[[https://magit.vc][Magit home page]]

#+begin_src emacs-lisp
  (use-package magit
    :defer t
    :bind ("C-x g" . magit-status))
#+end_src
** Move text with M-shift-up/down
#+begin_src emacs-lisp
  (use-package move-text
    :bind
    (("M-S-<up>" . move-text-up)
     ("M-S-<down>" . move-text-down)))
#+end_src
** Org mode
#+begin_src emacs-lisp
  (use-package org
    :straight nil
    :bind
    (:map org-mode-map
	  ("C-c l" . org-store-link))
    :config
    (setq org-agenda-files
	  `(,(expand-file-name "org-agenda" "~/Documents"))))
#+end_src
*** Org Babel load all languages when needed
Do not need to add any languages needed one-by-one. This slows down loading org files a bit.
[[https://emacs.stackexchange.com/questions/20577/org-babel-load-all-languages-on-demand][Stack Exchange answer used as source]]
#+begin_src emacs-lisp
  (defadvice org-babel-execute-src-block (around load-language nil activate)
    "Load language if needed."
    (let ((language (org-element-property :language (org-element-at-point))))
      (unless (cdr (assoc (intern language) org-babel-load-languages))
	(add-to-list 'org-babel-load-languages (cons (intern language) t))
	(org-babel-do-load-languages 'org-babel-load-languages org-babel-load-languages))
      ad-do-it))
#+end_src
** Rainbow delimiters
Really necessary for legibility of code blocks.
#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :hook
    ((prog-mode . rainbow-delimiters-mode)))
#+end_src
** Reading .epub books in Emacs
#+begin_src emacs-lisp
  (use-package nov-mode
    :straight
    (nov
     :type git :host nil
     :repo "https://depp.brause.cc/nov.el.git")
    :init
    (when (fboundp 'evil-set-initial-state)
      (evil-set-initial-state 'nov-mode 'emacs))
    :mode "\\.epub\\'")
#+end_src
** Smart parentheses
#+begin_src emacs-lisp
  (use-package smartparens
    :hook (prog-mode . smartparens-mode)
    :config
    (when (fboundp 'evil-leader/set-key)
      (evil-leader/set-key
	"p u" 'sp-up-sexp
	"p d" 'sp-down-sexp
	"p p" 'sp-previous-sexp
	"p e" 'sp-end-of-sexp
	"p a" 'sp-beginning-of-sexp
	"p j" 'sp-join-sexp))
    (require 'smartparens-config))
#+end_src
** Vertico
Buffer completion and vertical listing of options.
Savehist so vertico knows the last command used.
#+begin_src emacs-lisp
  (use-package vertico
    :init
    (vertico-mode)
    :config
    (setq completion-styles '(basic substring partial-completion flex)
	  read-file-name-completion-ignore-case t
	  read-buffer-completion-ignore-case t
	  completion-ignore-case t
	  vertico-cycle t))

  ;; Persist history over Emacs restarts.
  ;; Vertico sorts by history position.
  (use-package savehist
    :init
    (savehist-mode))
#+end_src
** Yasnippets
#+begin_src emacs-lisp
  (use-package yasnippet
    :hook (prog-mode . yas-minor-mode)
    :config
    (when (fboundp 'evil-leader/set-key)
      (evil-leader/set-key
	"i s" 'yas-insert-snippet)))

  (use-package yasnippet-snippets
    :after (yasnippet))
#+end_src
** Programming and markup languages support
Feel free to disable any languages you don't require by simply
running ~org-cut-subtree~ on the heading before exporting
*** Common Lisp (Sly)
#+begin_src emacs-lisp
  (use-package sly
    :defer t
    :config
    (setq-default sly-symbol-completion-mode nil)
    (setq org-babel-lisp-eval-fn #'sly-eval)
    (add-hook 'sly-mrepl-hook
	      (lambda ()
		(define-key sly-mrepl-mode-map
			    (kbd "M-r")
			    'comint-history-isearch-backward)))
    (setq inferior-lisp-program "sbcl"))
#+end_src
*** Go mode
#+begin_src emacs-lisp
  ;; install gopls lsp server
  (use-package go-ts-mode
    :when (fboundp 'treesit-install-language-grammar)
    :mode "\\.go\\'"
    :hook ((go-ts-mode . eglot-ensure)))
#+end_src
*** Haskell mode
Will move to tree-sitter later
#+begin_src emacs-lisp
  (use-package haskell-mode
    :straight (haskell-mode
	       :type git
	       :host github
	       :repo "haskell/haskell-mode")
    :mode "\\.hs\\'"
    :hook ((haskell-mode . eglot-ensure)
	   (haskell-mode . interactive-haskell-mode)))
#+end_src
*** HTML/CSS snippets (Emmet)
#+begin_src emacs-lisp
  (use-package emmet-mode
    :hook ((sgml-mode css-mode)))
#+end_src
*** Jenkinsfile mode
#+begin_src emacs-lisp
  (use-package jenkinsfile-mode
    :defer t)
#+end_src
*** Markdown mode
#+begin_src emacs-lisp
  (use-package markdown-mode
    :mode "\\.md\\'")
#+end_src
*** Python
Elpy functionality without elpy overhead.
#+begin_src emacs-lisp
  (use-package python-ts-mode
    :straight nil
    :when (fboundp 'treesit-install-language-grammar)
    :mode "\\.py\\'"
    :hook ((python-ts-mode . eglot-ensure))
    :config
    (setq python-interpreter "python3"))

  (use-package pyvenv
   :after (python-ts-mode))

  (use-package python-black
   :after (python-ts-mode))
#+end_src
*** Rust mode
#+begin_src emacs-lisp
  (use-package rust-ts-mode
    :straight nil
    :when (fboundp 'treesit-install-language-grammar)
    :mode "\\.rs\\'"
    :hook ((rust-ts-mode . eglot-ensure)))
#+end_src
*** Terraform mode
[[https://github.com/hcl-emacs/terraform-mode][Github page]]
#+begin_src emacs-lisp
  (use-package terraform-mode
    :mode "\\.tf\\'"
    :hook (terraform-mode . outline-minor-mode))
#+end_src
*** Uiua mode
An array language still in beta. I am working on the emacs mode currently.
#+begin_src emacs-lisp
  (use-package uiua-ts-mode
    :mode "\\.ua\\'")
#+end_src
*** Yaml mode
#+begin_src emacs-lisp
  (use-package yaml-ts-mode
    :when (fboundp 'treesit-install-language-grammar)
    :bind (:map yaml-ts-mode-map
		("C-m" . newline-and-indent))
    :mode "\\.ya?ml\\'")
#+end_src
** General emacs configuration
Removing menu bar, toolbar and scroll bar, which I don't really use, and binding C-x C-b to ibuffer, which is really pretty and nice.
#+begin_src emacs-lisp
  (use-package emacs
    :init
    (put 'dired-find-alternate-file 'disabled nil)
    ;; Add prompt indicator to `completing-read-multiple'.
    ;; We display [CRM<separator>], e.g., [CRM,]
    ;; if the separator is a comma.
    (defun crm-indicator (args)
      (cons (format "[CRM%s] %s"
		    (replace-regexp-in-string
		     "\\`\\[.*?]\\*\\|\\[.*?]\\*\\'" ""
		     crm-separator)
		    (car args))
	    (cdr args)))
    (advice-add #'completing-read-multiple :filter-args #'crm-indicator)

    ;; Do not allow the cursor in the minibuffer prompt
    (setq minibuffer-prompt-properties
	  '(read-only t cursor-intangible t face minibuffer-prompt))
    (add-hook 'minibuffer-setup-hook #'cursor-intangible-mode)
    (add-hook 'eshell-mode-hook (lambda () (display-line-numbers-mode 0)))
    (add-hook 'org-agenda-mode-hook (lambda () (display-line-numbers-mode 0)))
    ;; (add-hook 'pdf-view-mode-hook (lambda () (display-line-numbers-mode 0)))

    :bind
    (([remap list-buffers] . ibuffer)
      ;; https://www.masteringemacs.org/article/text-expansion-hippie-expand
     ([remap dabbrev-expand] . hippie-expand)
     ("C-<tab>" . dabbrev-completion))

    :config
    ;; Enable indentation+completion using the TAB key.
    ;; `completion-at-point' is often bound to M-TAB.
    (setq tab-always-indent 'complete)
    (setq-default use-short-answers t)
    (setq enable-recursive-minibuffers t)
    (setq ispell-program-name "aspell")
    (setq treesit-extra-load-path '("/usr/local/lib/tree-sitter"))
    (setq bookmark-save-flag 1)
    (windmove-default-keybindings)
    (global-display-line-numbers-mode)
    (pixel-scroll-precision-mode 1)
    (unless (eq system-type 'darwin)
      (menu-bar-mode -1))
    (scroll-bar-mode -1)
    (tool-bar-mode -1))
#+end_src
